name: BananoSuite
version: '${project.version}'
main: miner82.bananosuite.BananoSuitePlugin
api-version: 1.15
authors: [ Miner82 ]
depend: [Vault]
softdepend: [Essentials]
commands:
  bananosuite:
    description: OP commands to manage the plugin configuration.
  shields:
    description: OP-only command to prevent damage.
  donate:
    description: Donates the specified amount to the server.
  rain:
    description: Donates the specified amount to the server.
    aliases: [makeitrain]
  sethome:
    description: Sets the home co-ordinates for use with the /home command.
  teleport:
    description: Teleports the player to the specified location, for a fee. Additional QUOTE parameter to query the cost.
    aliases: [tp]
  spawn:
    description: Teleports the player to the world spawn coordinates, for a fee.
    aliases: [tps]
  home:
    description: Teleports the player to the world spawn coordinates, for a fee.
    aliases: [tph]
  deathinsurance:
    description: Toggles Death insurance on/off, or offers a policy quote.
    aliases: [di]
#  pvptoggle:
#    description: Toggles PvP on/off.
  monkeymap:
    description: Provides the ability to buy a map displaying the monKey or QR code for your Banano address.
  help:
    description: Displays a list of commands and possible parameters.